### ISSUE TITLE
無法正常使用

### ISSUE THREAD

**Issue by flier268** [EYHN/telegram-search#1]
我的目標是在一個不公開的群組裡面添加bot，用來搜尋群組裡面的訊息
Bot是在群組裡面，並且只有群組內的人可以查詢對話紀錄(透過在逡組內輸入/search [Keyword])

我依照Readme裡面的步驟，但還是不法順利架設
因為我無需Client，所以我把[這段](https://github.com/EYHN/telegram-search/blob/master/main.py#L156)刪除了

我有以下疑惑：
* 如果沒有手動建立session資料夾，則會出現錯誤 __(sqlite3.OperationalError: unable to open database file)__
* 架設步驟漏掉了REDIS、elasticsearch，這邊應該依照預設值安裝就好了吧
* 如果Bot也在群組內，則[這段](https://github.com/EYHN/telegram-search/blob/master/main.py#L139)應該改 __event.chat_id__ 為 __event.from_id__
* /download_history後，TG會回應"開始下載歷史記錄"，但就沒有後續動作了
* 可以搜尋私訊紀錄嗎?

**Comment by EYHN** [comment]
telegram bot无法监控消息内容，所以需要一个Client，Client是必须的不能删除。
