### ISSUE TITLE
无法下载历史记录？

### ISSUE THREAD

**Issue by ron159** [EYHN/telegram-search#4]
/download_history 之后，提示开始下载历史记录，然后就卡住没反应了，看了一下后端，telegram-search_elasticsearch_1这个container会不断自动重启。
想问问是什么原因呢？

**Comment by EYHN** [comment]
一般是java jvm内存不够

**Comment by ron159** [comment]
> 一般是java jvm内存不够

好的，谢谢，我尝试改大一些
